apiVersion: v1
kind: Secret
metadata:
  name: sonar-postgresql
  namespace: default
type: Opaque
data:
  postgres-password: c29uYXJQYXNz # For postgres admin
  password: c29uYXJQYXNz # For sonarUser custom user
  replication-password: c29uYXJQYXNz # For replication
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgresql-jdbc
  namespace: default
type: Opaque
data:
  jdbc-username: c29uYXJVc2Vy
  jdbc-password: c29uYXJQYXNz
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-pgadmin4
  namespace: default
type: Opaque
data:
  password: c29uYXJVc2Vy
